# Generated by Django 4.0.4 on 2022-05-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('shelf_id', models.IntegerField()),
                ('good_thru', models.DateField()),
                ('observation', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
